name: DiscordBridge
author: Falyrion
description: DiscordBridge
version: 1.1.0.0
api-version: 1.17

main: com.falyrion.discordbridge.DiscordBridgeMain

commands:
  discord:
    usage: /discord
    description: Shows the player a clickable link to a discord server in the chat
    permission: discordbridge.getlink
